# Default configuration for tftldr

ignore:
  # Resource type prefixes to ignore
  prefixes:
    - "random_"
    - "time_"

  # Exact resource types to ignore
  types:
    - "terraform_data"
    - "null_resource"

# Column visibility settings
columns:
  resourceAddress: true # Show the Terraform resource address
